language: node_js
before_deploy: "echo 'ready?'"
install: skip
script:
  return 0
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "kunal76765437"